source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BlockTimer_Example', :exclusive => true do
  pod 'BlockTimer', :path => '../'
end

target 'BlockTimer_Tests', :exclusive => true do
  pod 'BlockTimer', :path => '../'

  
end
